#!/usr/bin/expect -f
set timeout -1
set password "&m5L9\[eUv"

spawn scp -o StrictHostKeyChecking=no update_medical_fixes.tar.gz ubutu@112.78.15.2:/tmp/update_medical_fixes.tar.gz
expect "password:"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no ubutu@112.78.15.2
expect "password:"
send "$password\r"
expect "$ "
send "echo '&m5L9\[eUv' | sudo -S tar -xzvf /tmp/update_medical_fixes.tar.gz -C /var/www/crm_phong_kham/ \r"
expect "$ "
send "echo '&m5L9\[eUv' | sudo -S chown -R www-data:www-data /var/www/crm_phong_kham/\r"
expect "$ "
send "exit\r"
expect eof
