#!/usr/bin/expect -f
set timeout -1
set password {&m5L9[eUv}

puts "Tai len file..."
spawn scp -o StrictHostKeyChecking=no modules/patients/index.php modules/patients/add.php modules/patients/edit.php ubutu@112.78.15.2:/tmp/
expect { "*assword:*" { send "$password\r"; exp_continue } eof }

puts "Copy vao dung thu muc..."
spawn ssh -o StrictHostKeyChecking=no ubutu@112.78.15.2 "echo '&m5L9\[eUv' | sudo -S cp /tmp/index.php /var/www/crm_phong_kham/modules/patients/index.php && echo '&m5L9\[eUv' | sudo -S cp /tmp/add.php /var/www/crm_phong_kham/modules/patients/add.php && echo '&m5L9\[eUv' | sudo -S cp /tmp/edit.php /var/www/crm_phong_kham/modules/patients/edit.php && echo '&m5L9\[eUv' | sudo -S chown www-data:www-data /var/www/crm_phong_kham/modules/patients/index.php /var/www/crm_phong_kham/modules/patients/add.php /var/www/crm_phong_kham/modules/patients/edit.php && rm /tmp/index.php /tmp/add.php /tmp/edit.php"
expect { "*assword:*" { send "$password\r"; exp_continue } eof }

puts "Xong!"
