#!/usr/bin/expect -f
set timeout -1
set password {&m5L9[eUv}

spawn scp -o StrictHostKeyChecking=no includes/invoice_popup.php modules/billing/search_coin_patients_api.php ubutu@112.78.15.2:/tmp/
expect {
    "*assword:*" {
        send "$password\r"
        exp_continue
    }
    eof
}

spawn ssh -o StrictHostKeyChecking=no ubutu@112.78.15.2 "echo '&m5L9\[eUv' | sudo -S cp /tmp/invoice_popup.php /var/www/crm_phong_kham/includes/invoice_popup.php && echo '&m5L9\[eUv' | sudo -S cp /tmp/search_coin_patients_api.php /var/www/crm_phong_kham/modules/billing/search_coin_patients_api.php && echo '&m5L9\[eUv' | sudo -S chown www-data:www-data /var/www/crm_phong_kham/includes/invoice_popup.php /var/www/crm_phong_kham/modules/billing/search_coin_patients_api.php && rm /tmp/invoice_popup.php /tmp/search_coin_patients_api.php"
expect {
    "*assword:*" {
        send "$password\r"
        exp_continue
    }
    eof
}
