ALTER TABLE packages MODIFY total_price DECIMAL(15,2) NOT NULL;
ALTER TABLE products MODIFY price DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE invoices MODIFY subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE invoices MODIFY discount_amount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE invoices MODIFY total_amount DECIMAL(15,2) NOT NULL;
ALTER TABLE invoices MODIFY cash_amount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE invoices MODIFY transfer_amount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE invoices MODIFY package_deduct DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE invoices MODIFY debt_amount DECIMAL(15,2) DEFAULT 0.00;
