import json

with open('translate_dict_en.json', 'r') as f:
    data = json.load(f)

# Fill in the rest
mapping = {
    "intermittierend / wechselhaft": "Intermittent / Variable",
    "sporadisch": "Sporadic",
    "eingeschränkt": "Restricted Movement",
    "Treppe abwärts": "Stairs Down",
    "Treppe aufwärts": "Stairs Up",
    "akut seit": "Acute since",
    "wiederkehrend seit": "Recurrent since",
    "chronisch seit": "Chronic since",
    "Fuß": "Foot",
    "Schwierigkeiten beim": "Difficulty with",
    "Hatte Operation": "Had Surgery",
    "Verlauf im Vergleich zur letzten Behandlung:": "Progress compared to last treatment:",
    "Position": "Position",
    "Carpaltunnelsyndrom - CTS": "Carpal Tunnel Syndrome (CTS)",
    "außen - Ulnarseite": "Outside - Ulnar side",
    "LEGENDE ZUR SCHMERZINTENSITÄT (5 KREISE):": "PAIN INTENSITY LEGEND (5 CIRCLES):",
    "Legende zur Schmerzintensität (5 Kreise):": "Pain Intensity Legend (5 Circles):",
    "1x/M": "1x/Month",
    "hat Brücken": "Has Bridges",
    "hatte Zahnspange": "Had Braces",
    "Ventral - li": "Ventral - L",
    "Deutlich verbessert.": "Significantly improved.",
    "Kiefergelenk": "Temporomandibular Joint (TMJ)",
    "Hinweis: Grau markierte Felder wurden in der letzten Sitzung behandelt. Sie können diese überschreiben, um sie für dieses Mal zu aktualisieren.": "Note: Gray highlighted fields were treated in the last session. You can overwrite them to update for this time.",
    "Leicht verbessert.": "Slightly improved.",
    "hat wurzelbehandelte Zähne": "Has Root Canal Treated Teeth",
    "hat Kronen": "Has Crowns",
    "Hand & Handgelenk": "Hand & Wrist",
    "Rippe": "Rib",
    "Daumen/Pollicis": "Thumb (Pollicis)",
    "Ring 1 (hellblau):": "Ring 1 (Light Blue):",
    "Ring 1 (hellblau)": "Ring 1 (Light Blue)",
    "seit wann:": "Since when:",
    "Ohrgeräusch": "Tinnitus",
    "Weiter": "Next",
    "Dorsal": "Dorsal",
    "Ring 5 (rot)": "Ring 5 (Red)",
    "Ring 5 (rot):": "Ring 5 (Red):",
    "Ring 3 (gelb):": "Ring 3 (Yellow):",
    "Ring 3 (gelb)": "Ring 3 (Yellow)",
    "Justierungsbereich - HWS": "Adjustment Area - Cervical Spine",
    "Justierungsbereich - BWS": "Adjustment Area - Thoracic Spine",
    "Justierungsbereich - LWS": "Adjustment Area - Lumbar Spine",
    "Ventral - re": "Ventral - R",
    "li | re": "L | R",
    "TEIL 2 – AKTUELLE BESCHWERDEN": "PART 2 - CURRENT COMPLAINTS",
    "hat Implantate": "Has Implants",
    "medial/innen": "Medial/Inside",
    "Deutlich verschlechtert.": "Significantly worsened.",
    "phasenweise beschwerdefrei": "Intermittently pain-free",
    "Taubheit": "Numbness",
    "Ring 4 (orange)": "Ring 4 (Orange)",
    "Ring 4 (orange):": "Ring 4 (Orange):",
    "Zehe": "Toe",
    "Finger/Digiti": "Fingers (Digiti)",
    "dorsal/hinten": "Dorsal/Back",
    "Ausstrahlung in eine bestimmte Richtung": "Radiation in specific direction",
    "lateral/außen": "Lateral/Outside",
    "2-3x/W": "2-3x/Week",
    "Gelenkblockade": "Joint Blockage",
    "rauschen": "Rushing",
    "1x/W": "1x/Week",
    "Weitere Notizen zur Anamnese eingeben...": "Enter additional anamnesis notes...",
    "Anamnese-Notizen": "Anamnesis Notes",
    "gesamt": "Total",
    "wie oft:": "How often:",
    "(Gelbes O auf dem Bild oben markieren)": "(Mark Yellow O on the image above)",
    "Unverändert (Schmerzen wie zuvor).": "Unchanged (Pain as before).",
    "Wirbel": "Vertebra",
    "Bekannte Beinlängendifferenz": "Known Leg Length Discrepancy",
    "Tennisarm - TA": "Tennis Elbow (TA)",
    "Bewegung eingeschränkt nach:": "Movement restricted to:",
    "kurzes Bein": "Short Leg",
    "Golferarm - GA": "Golfer's Elbow (GA)",
    "Bild auswählen, auf <strong>Hochladen</strong> klicken, dann am Ende der Seite auf <strong>Speichern</strong> klicken, um abzuschließen.": "Select image, click <strong>Upload</strong>, then click <strong>Save</strong> at the bottom of the page to complete.",
    "Bewegung": "Movement",
    "Abbrechen": "Cancel",
    "Ring 2 (grün):": "Ring 2 (Green):",
    "Ring 2 (grün)": "Ring 2 (Green)",
    "Ventral": "Ventral",
    "Knacken": "Cracking",
    "Behandlungs- & Justierungsliste": "Treatment & Adjustment List",
    "Schmerzen": "Pain",
    "Ruhe": "Rest",
    "ventral/vorne": "Ventral/Front",
    "Hatte Fraktur": "Had Fracture",
    "Leiste/Flanke": "Groin/Flank",
    "permanent": "Permanent",
    "hat Zahnspange": "Has Braces",
    "Metacarpalia - MTC": "Metacarpals (MTC)",
    "bei:": "During:",
    "Nur Historie ansehen, keine Bearbeitung.": "View History Only, No Editing.",
    "Schmerzskala:": "Pain Scale:",
    "Behandlungsnotizen HEUTE": "Treatment Notes TODAY",
    "Wenn kein vorheriges Bild vorhanden ist, wird das aus der Anamnese übernommen. Das vorherige Bild kann nur angesehen, nicht bearbeitet werden. Das aktuelle Bild übernimmt die Operations- und Frakturmarkierungen des vorherigen. Hier werden nur die 5 Schmerzstufen verwendet.": "If no previous image exists, it's taken from the anamnesis. The previous image can only be viewed, not edited. The current image inherits the surgery and fracture marks of the previous one. Only the 5 pain levels are used here.",
    "palmar": "Palmar",
    "innen - Daumenseite": "Inside - Thumb side",
    "Operations- und Trauma-Anamnese": "Surgical and Trauma History",
    "Zurück": "Back",
    "Dorsal - re": "Dorsal - R",
    "Leicht verschlechtert.": "Slightly worsened.",
    "Dorsal - li": "Dorsal - L",
    "Zeitpunkt": "Time",
}

for item in data:
    if not item['en']:
        item['en'] = mapping.get(item['de'].strip(), item['de'])

with open('translate_dict_en.json', 'w') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
